### ISSUE TITLE
Prettify linting on OUJS?

### ISSUE THREAD

**Issue by Martii** [cvzi/Userscripts#4]
Hey there... here under non-official capacity.

I was wondering if you would consider some minor additions to your code with [some options](https://jshint.com/docs/options/) for what I would consider a better presentation reception on the site for the newbies.

Ex.

``` diff
--- /scripts/cuzi/Paywall_redirect_to_Archive.today/source@2.15+06ad619
+++ /scripts/cuzi/Paywall_redirect_to_Archive.today/source
@@ -37,6 +37,8 @@
 // ==/UserScript==
 
 /* global GM */
+/* jshint asi: true */
+/* jshint esversion: 8 */
 
 (async function () {
   'use strict'

```

This would get rid of most source code page exclamation points for your preference of not using semicolons, and most warning triangles specific to the script referenced in this diff. 

I know it's cosmetic but ya know. :smile_cat: 

Thanks for the consideration either way.

---

P.S. Or a one liner of:

``` diff
--- /scripts/cuzi/Paywall_redirect_to_Archive.today/source@2.15+06ad619
+++ /scripts/cuzi/Paywall_redirect_to_Archive.today/source
@@ -37,6 +37,7 @@
 // ==/UserScript==
 
 /* global GM */
+/* jshint asi: true, esversion: 8 */
 
 (async function () {
   'use strict'
```

... should work too.

**Comment by cvzi** [comment]
Thank you for the details, I was not aware of these options. The warning triangles did bother me a bit, but frankly I never investigated. I tend to use [standardjs](https://standardjs.com/) for linting.

I'll include your suggestions.
